<a href="https://colab.research.google.com/github/Bharathkumar4281/project/blob/main/Sentimental_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import the dataset and do the data preprocessing
#problem statement
# Develop a sentiment analysis model to classify reviews as positive or negetive.
#preprocess the review text using techniques such as lower casting,removing stop words and lemmatization
# use the trained model accuratly protect the sentiment
import pandas as pd
data=pd.read_csv('Reviews.csv')
print(data)
                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]
# we can reviw the top5 rows
data.head()
Review	Liked
0	Wow... Loved this place.	1
1	Crust is not good.	0
2	Not tasty and the texture was just nasty.	0
3	Stopped by during the late May bank holiday of...	1
4	The selection on the menu was great and so wer...	1
#we can the top 10 rows
data.head(10)
Review	Liked
0	Wow... Loved this place.	1
1	Crust is not good.	0
2	Not tasty and the texture was just nasty.	0
3	Stopped by during the late May bank holiday of...	1
4	The selection on the menu was great and so wer...	1
5	Now I am getting angry and I want my damn pho.	0
6	Honeslty it didn't taste THAT fresh.)	0
7	The potatoes were like rubber and you could te...	0
8	The fries were great too.	1
9	A great touch.	1
data.tail()    # last 5 rows
Review	Liked
995	I think food should have flavor and texture an...	0
996	Appetite instantly gone.	0
997	Overall I was not impressed and would not go b...	0
998	The whole experience was underwhelming, and I ...	0
999	Then, as if I hadn't wasted enough of my life ...	0
data.tail(10)   #last 10 rows
Review	Liked
990	The refried beans that came with my meal were ...	0
991	Spend your money and time some place else.	0
992	A lady at the table next to us found a live gr...	0
993	the presentation of the food was awful.	0
994	I can't tell you how disappointed I was.	0
995	I think food should have flavor and texture an...	0
996	Appetite instantly gone.	0
997	Overall I was not impressed and would not go b...	0
998	The whole experience was underwhelming, and I ...	0
999	Then, as if I hadn't wasted enough of my life ...	0
data.info() #dataset info like datatypes,entries of dataset and memory usage
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB
data.isnull().sum() # checking the null values
Review    0
Liked     0
dtype: int64
data.duplicated() #checking the duplicated data
0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool
import seaborn as sns
import matplotlib.pyplot as plt
pip install wordcloud
Requirement already satisfied: wordcloud in c:\users\venkatavaibhav\anaconda3\lib\site-packages (1.9.3)
Requirement already satisfied: numpy>=1.6.1 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from wordcloud) (1.26.4)
Requirement already satisfied: pillow in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from wordcloud) (10.2.0)
Requirement already satisfied: matplotlib in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from wordcloud) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
from wordcloud import WordCloud
combined_text=" ".join(data['Review']) #Combine all review text into one string
wordcloud=WordCloud(width=800,height=400,background_color='white').generate(combined_text)
plt.figure(figsize=(10,6))
plt.imshow(wordcloud,interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Reviews')
plt.show()

from collections import Counter
targeted_words=['good','great','amazing','bad']
all_words=" ".join(data['Review']).lower().split()     #flattened reviews into a single list of words
word_counts=Counter(all_words)
target_word_count={word:word_counts[word] for word in targeted_words}
#plotting
plt.figure(figsize=(8,6))
plt.bar(target_word_count.keys(),target_word_count.values(),color=['blue','green','orange','red'])
plt.xlabel('Words')
plt.ylabel('Frequency')
plt.title('Frequency of specific words in reviews')
plt.show()

lowercases_text=data['Review'].str.lower()
print(lowercases_text)
0                               wow... loved this place.
1                                     crust is not good.
2              not tasty and the texture was just nasty.
3      stopped by during the late may bank holiday of...
4      the selection on the menu was great and so wer...
                             ...
995    i think food should have flavor and texture an...
996                             appetite instantly gone.
997    overall i was not impressed and would not go b...
998    the whole experience was underwhelming, and i ...
999    then, as if i hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object
#tokenization
from nltk.tokenize import word_tokenize
import nltk
#Download the'punkt' tokenizer
nltk.download('punkt')
[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
False
data['Tokens'] = data['Review'].apply(word_tokenize)
print(data ['Tokens'] )
0                      [Wow, ..., Loved, this, place, .]
1                              [Crust, is, not, good, .]
2      [Not, tasty, and, the, texture, was, just, nas...
3      [Stopped, by, during, the, late, May, bank, ho...
4      [The, selection, on, the, menu, was, great, an...
                             ...
995    [I, think, food, should, have, flavor, and, te...
996                       [Appetite, instantly, gone, .]
997    [Overall, I, was, not, impressed, and, would, ...
998    [The, whole, experience, was, underwhelming, ,...
999    [Then, ,, as, if, I, had, n't, wasted, enough,...
Name: Tokens, Length: 1000, dtype: object
data.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64
 2   Tokens  1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Venkatavaibhav\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
True
stop_words=set(stopwords.words('english'))
data['Tokens']=data['Review'].apply(lambda x:[word for word in word_tokenize(x) if word not in stop_words])
print(data['Tokens'])
0                            [Wow, ..., Loved, place, .]
1                                       [Crust, good, .]
2                        [Not, tasty, texture, nasty, .]
3      [Stopped, late, May, bank, holiday, Rick, Stev...
4               [The, selection, menu, great, prices, .]
                             ...
995        [I, think, food, flavor, texture, lacking, .]
996                       [Appetite, instantly, gone, .]
997          [Overall, I, impressed, would, go, back, .]
998    [The, whole, experience, underwhelming, ,, I, ...
999    [Then, ,, I, n't, wasted, enough, life, ,, pou...
Name: Tokens, Length: 1000, dtype: object
#stemming
from nltk.stem import PorterStemmer
Stemmer=PorterStemmer()
data['stemmed']=data['Review'].apply(lambda x:"".join([Stemmer.stem(word) for word in word_tokenize(x)]))
print(data['stemmed'])
data['stemmed'].value_counts()
0                                    wow...lovethiplace.
1                                        crustisnotgood.
2                       nottastiandthetexturwajustnasti.
3      stopbydurethelatemaybankholidayoffricksteverec...
4            theselectonthemenuwagreatandsoweretheprice.
                             ...
995    ithinkfoodshouldhaveflavorandtexturandbothwere...
996                                appetitinstantligone.
997                overaliwanotimpressandwouldnotgoback.
998    thewholeexperiwaunderwhelm,andithinkwe'lljustg...
999    then,asifihadn'twastenoughofmylifethere,theypo...
Name: stemmed, Length: 1000, dtype: object
stemmed
#name?                                                                                                  4
thefoodwaterribl.                                                                                       2
iwouldnotrecommendthiplace.                                                                             2
ilovethiplace.                                                                                          2
iwon'tbeback.                                                                                           2
                                                                                                       ..
omg,thefoodwadelicioso!                                                                                 1
thereisnothauthentaboutthiplace.                                                                        1
thespaghettiisnothspecialwhatsoev.                                                                      1
ofallthedish,thesalmonwathebest,butallweregreat.                                                        1
then,asifihadn'twastenoughofmylifethere,theypoursaltinthewoundbydrawoutthetimeittooktobringthecheck.    1
Name: count, Length: 993, dtype: int64
#Lemmatization
import nltk
nltk.download('wordnet')
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Venkatavaibhav\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
True
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
lemmatizer=WordNetLemmatizer()
data['Lemmatized']=data['Review'].apply(lambda x:''.join([lemmatizer.lemmatize(word,pos=wordnet.VERB)for word in word_tokenize(x)]))
print(data['Lemmatized'])
0                                  Wow...Lovedthisplace.
1                                        Crustbenotgood.
2                      Nottastyandthetexturebejustnasty.
3      StoppedbyduringthelateMaybankholidayoffRickSte...
4           Theselectiononthemenubegreatandsobetheprice.
                             ...
995    Ithinkfoodshouldhaveflavorandtextureandbothbel...
996                                 Appetiteinstantlygo.
997               OverallIbenotimpressandwouldnotgoback.
998    Thewholeexperiencebeunderwhelming,andIthinkwe'...
999    Then,asifIhaven'twasteenoughofmylifethere,they...
Name: Lemmatized, Length: 1000, dtype: object
#removing the numbers
import re
data['No_Numbers']=data['Review'].apply(lambda x:re.sub(r'\d+','',x))
print(data['No_Numbers'])
0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: No_Numbers, Length: 1000, dtype: object
data["cleaned_text"]=data['Review'].apply(lambda x:re.sub(r'[^A-Za-z0-9\s]','',x))
print(data["cleaned_text"])
0                                   Wow Loved this place
1                                      Crust is not good
2               Not tasty and the texture was just nasty
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                              Appetite instantly gone
997    Overall I was not impressed and would not go back
998    The whole experience was underwhelming and I t...
999    Then as if I hadnt wasted enough of my life th...
Name: cleaned_text, Length: 1000, dtype: object
data.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Review        1000 non-null   object
 1   Liked         1000 non-null   int64
 2   Tokens        1000 non-null   object
 3   stemmed       1000 non-null   object
 4   Lemmatized    1000 non-null   object
 5   No_Numbers    1000 non-null   object
 6   cleaned_text  1000 non-null   object
dtypes: int64(1), object(6)
memory usage: 54.8+ KB
pip install contractions
Requirement already satisfied: contractions in c:\users\venkatavaibhav\anaconda3\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.2)
Requirement already satisfied: pyahocorasick in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (2.1.0)
Note: you may need to restart the kernel to use updated packages.
#normalization
import contractions
data['Expanded'] = data['Review'].apply(contractions.fix)
print(data['Expanded'])
0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I had not wasted enough of my life...
Name: Expanded, Length: 1000, dtype: object
pip install emoji
Collecting emoji
  Downloading emoji-2.12.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: typing-extensions>=4.7.0 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from emoji) (4.9.0)
Downloading emoji-2.12.1-py3-none-any.whl (431 kB)
   ---------------------------------------- 0.0/431.4 kB ? eta -:--:--
    --------------------------------------- 10.2/431.4 kB ? eta -:--:--
   -- ------------------------------------ 30.7/431.4 kB 435.7 kB/s eta 0:00:01
   ----- --------------------------------- 61.4/431.4 kB 656.4 kB/s eta 0:00:01
   ------------------ --------------------- 204.8/431.4 kB 1.6 MB/s eta 0:00:01
   ---------------------------------------  430.1/431.4 kB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 431.4/431.4 kB 2.3 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.12.1
Note: you may need to restart the kernel to use updated packages.
import emoji
data['Emoji'] = data['Review'].apply(emoji.demojize)
print(data['Emoji'])
0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Emoji, Length: 1000, dtype: object
pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\venkatavaibhav\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.
from bs4 import BeautifulSoup
data['Cleaned'] = data['Review'].apply(lambda x: BeautifulSoup(x,"html.parser").get_text())
print(data['Cleaned'])
0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Cleaned, Length: 1000, dtype: object
C:\Users\Venkatavaibhav\AppData\Local\Temp\ipykernel_10064\4263549124.py:2: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  data['Cleaned'] = data['Review'].apply(lambda x: BeautifulSoup(x,"html.parser").get_text())
#TF -IDF VECTORIZER
#TF = TERM FREQUENCY,IDF = INVERSE DOCUMENT FREQUENCY
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X = vectorizer.fit_transform(data['Review'])
print(X.toarray())
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#Building the machine learning model
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['Review'])
y = data['Liked']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)
print(X_train,X_test,y_train,y_test)
  (0, 1527)	0.578582388550776
  (0, 1516)	0.5587881819736206
  (0, 2005)	0.45560954528848707
  (0, 1938)	0.20794801889277578
  (0, 1778)	0.3196494189359375
  (1, 711)	0.4193390530637025
  (1, 622)	0.4193390530637025
  (1, 1180)	0.3554925882290983
  (1, 613)	0.32026666852400937
  (1, 1471)	0.272554926639921
  (1, 62)	0.5164170315313602
  (1, 263)	0.27998403419950374
  (2, 1057)	0.5102287539842273
  (2, 1962)	0.48790050997574835
  (2, 699)	0.3031291394604372
  (2, 1618)	0.5102287539842273
  (2, 1571)	0.3198299691276987
  (2, 1938)	0.21704341786509082
  (3, 1723)	0.4538927163856403
  (3, 1852)	0.42838721919777234
  (3, 719)	0.30305480231081033
  (3, 1791)	0.3192733609259723
  (3, 821)	0.37508854376741335
  (3, 590)	0.33614831815132157
  (3, 1471)	0.29501353406759745
  :	:
  (797, 1796)	0.2155139089210878
  (798, 649)	0.34296597014320795
  (798, 787)	0.34296597014320795
  (798, 17)	0.34296597014320795
  (798, 406)	0.32369375609078
  (798, 18)	0.34296597014320795
  (798, 122)	0.34296597014320795
  (798, 1320)	0.29941363785664343
  (798, 890)	0.2907476885588123
  (798, 1206)	0.14757149730549846
  (798, 1776)	0.1774987010047913
  (798, 944)	0.14171411086951774
  (798, 1938)	0.2228482091437908
  (798, 63)	0.09941818111459709
  (799, 158)	0.3964954268406326
  (799, 279)	0.4286481233974752
  (799, 1371)	0.36691217304779694
  (799, 1835)	0.36691217304779694
  (799, 179)	0.2837174144687825
  (799, 245)	0.341391142036711
  (799, 699)	0.20607571915436035
  (799, 915)	0.20607571915436035
  (799, 2025)	0.24443151499428203
  (799, 944)	0.1876634520751288
  (799, 1778)	0.11340570263380041   (0, 762)	0.47256008939307
  (0, 830)	0.5227794349477328
  (0, 850)	0.2788148086554363
  (0, 903)	0.32903415421009913
  (0, 756)	0.29720151212237056
  (0, 2025)	0.28135721691301263
  (0, 1197)	0.387165119592869
  (1, 1658)	0.4103419207551196
  (1, 45)	0.4103419207551196
  (1, 1781)	0.29575708998809846
  (1, 621)	0.2766223654390893
  (1, 1851)	0.32480705768080226
  (1, 1633)	0.27939699659872946
  (1, 716)	0.26026227204972024
  (1, 696)	0.17703009835601147
  (1, 915)	0.18618945297796038
  (1, 1812)	0.15350378435384465
  (1, 1571)	0.19644751772739483
  (1, 1778)	0.1024620747393945
  (1, 63)	0.11894896563501532
  (1, 1759)	0.3084469642914332
  (2, 641)	0.36530419498595135
  (2, 339)	0.35132051079261234
  (2, 654)	0.3398950088821647
  (2, 1471)	0.5877990721015991
  :	:
  (198, 73)	0.39191145656618687
  (198, 719)	0.30866733735581975
  (198, 1641)	0.35918322904387284
  (198, 1982)	0.27535929343010807
  (198, 850)	0.24655854617575115
  (198, 155)	0.2373165782739377
  (198, 696)	0.19944536250717973
  (198, 745)	0.3659336009279139
  (198, 1194)	0.2043973840668572
  (199, 245)	0.3138625483855926
  (199, 1057)	0.31889764742751303
  (199, 1894)	0.27621491029163275
  (199, 1815)	0.3645234154260868
  (199, 1552)	0.3774360932885095
  (199, 1780)	0.2608394295039084
  (199, 1370)	0.284302533387564
  (199, 1812)	0.15619894024506778
  (199, 1807)	0.24136874538352923
  (199, 166)	0.27621491029163275
  (199, 944)	0.17253092436945436
  (199, 1938)	0.135654125343441
  (199, 1778)	0.10426106142577002
  (199, 63)	0.12103742232574498
  (199, 763)	0.19662646224587704
  (199, 942)	0.16732136895679153 29     0
535    1
695    0
557    0
836    1
      ..
106    1
270    1
860    1
435    0
102    1
Name: Liked, Length: 800, dtype: int64 521    1
737    1
740    1
660    1
411    1
      ..
408    1
332    1
208    0
613    0
78     1
Name: Liked, Length: 200, dtype: int64
model=MultinomialNB()
model.fit(X_train,y_train)
MultinomialNB()
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.
y_pred=model.predict(X_test)
accuracy= accuracy_score(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(f'Accuracy:{accuracy}')
print('Classification Report')
print(report)
Accuracy:0.8
Classification Report
              precision    recall  f1-score   support

           0       0.76      0.85      0.80        96
           1       0.85      0.75      0.80       104

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.81      0.80      0.80       200

#prediction sentiment fro new review
def predict_sentiment(new_review):
    # Assuming you have a preprocess_text function defined elsewhere
    cleaned_review=preprocess_text(new_review) # Apply preprocessing to the new review
    X_new = vectorizer.transform([cleaned_review]) # Transform the cleaned review using the fitted vectorizer
    return model.predict(X_new)[0] # Predict the sentiment using the trained model

# Get new reviews from user input
new_reviews= input("enter a review:")
# Iterate through each review in the input
for review in new_reviews:
    sentiment = predict_sentiment(review) # Predict the sentiment of the current review
    sentiment_label='Positive' if sentiment ==1 else "Negative" # Assign sentiment label based on prediction
    print(f"Review:'{review}' \nSentiment: {sentiment_label}") # Print the review and its predicted sentiment

IndentationError: unexpected indent (<ipython-input-3-7d70c706d5e9>, line 9)